import { SessionWrapper } from "./components/SessionWrapper";
import "./globals.css";

export const metadata:{title:string,description:string} = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children}:{children:React.ReactNode} ) {
  return (
    <html lang="en">
      <body className="min-h-full flex flex-col">
      <SessionWrapper>
        {children}
      </SessionWrapper>
      </body>
    </html>
  );
}